lang: minimal
os: osx

# Refer to: https://docs.travis-ci.com/user/reference/osx/#macos-version
#
# Homebrew is expected to work on MacOS 10.12 and newer.  Some formulae can be
# compiled on older systems as well, but not Botan.  Therefore, xcode7.3 image
# is not included in following list.
osx_image:
  - xcode10.2
  - xcode9.4
  - xcode8.3

env:
  global:
    - TAP_NAME=riboseinc/rnp
    - FORMULA_NAME=${TAP_NAME}/rnp
    - OPTS=""
    - BINTRAY_SUBJECT=skalee
    - BINTRAY_REPO=Homebrew
    - BINTRAY_PACKAGE=rnp

install:
  - brew update
  - brew tap ${TAP_NAME} "${TRAVIS_BUILD_DIR}"
  - brew install --build-bottle ${FORMULA_NAME} ${OPTS}

script:
  - brew test ${FORMULA_NAME}

matrix:
  include:
    # Install HEAD version
    - env: OPTS="--HEAD"

  allow_failures:
    - env: OPTS="--HEAD"

before_deploy:
  - brew install jq
  - brew bottle rnp --json
  - source ci/read_bottle_metadata.sh
  - ci/build_bintray_descriptor.rb

deploy:
  provider: bintray
  skip_cleanup: true # prevents from removing build artifacts
  file: bintray_descriptor.json # built in build_bintray_descriptor.rb
  user: skalee
  key:
    secure: "J/waDRL47iayO5Ar/ySVpc9r8/EIBcaZBZFsi6CeQRQ4Oej5RxR0QtsCycDI312ZWGaqb8+ZiG060ZLF+ZIBcLAeudjv7D1YOX5+TXQ7tZHDjLlX9QJs6sq2E3GcblmALIRERyr5OJbb94F3wsn7B7867pwk2u5fCu+JMRjTSaxigtK0WFCdU0QxrCdqYqDr9emj8M4jQcNHkDysADRmOxzU6zuhz0LshjN/4LPyz25+TQPmXOaDvCLPwtI4C07dY8r41OtxtmJwXpX02uIfKLIjwkdEaB+DSTQ1ew8fGYgnR0l3kGJMr5ArkTd8OIFhLC/tW32S+kYbr97CZ+EEKS+7gDs3VdkhOlvzZ8QazNYKyvum/OMQ8N9msWHbUnqG9V8iXlIVK9Qpw3iSZjvE950Hon92Bu7ra/3xFhuywW5hWysSeMCkMCv+5+kAKp4YedSY8eYPDO16e5flvJhuk7T1ZSl+6sw1w3OX0PG/a++B507krX0YpbreTr8OBZqnkDgLoxfl5dflq1Jjyd05ksrmljJTcSEV9J5iZGMva+BJlHXTPJfvxlMF2y9Foc3D5qMsgVbZrLnhaGzeulxsJ0bCQmg7KUJOoJQLhAtZfIoaWmBZWAvA23DxShh01EB1UPqMdY7NfFUM1bdi9us7IkD5MhWLFRSyApSAiBm1eg8="
  on:
    repo: riboseinc/homebrew-rnp
    branch: bintray
